const OTP_REQUEST = "OTP_REQUEST";
const OTP_REQUEST_SUCCESS = "OTP_REQUEST_SUCCESS";
const OTP_REQUEST_FAILURE = "OTP_REQUEST_FAILURE";
const OTP_VERIFY_REQUEST = "OTP_VERIFY_REQUEST";
const OTP_VERIFY_SUCCESS = "OTP_VERIFY_SUCCESS";
const OTP_VERIFY_FAILURE = "OTP_VERIFY_FAILURE";
const LOGOUT_USER = "LOGOUT_USER";
const LOGOUT_USER_SUCCESS = "LOGOUT_USER_SUCCESS";
const LOGOUT_USER_FAILURE = "LOGOUT_USER_FAILURE";
export {
  OTP_REQUEST,
  OTP_REQUEST_SUCCESS,
  OTP_REQUEST_FAILURE,
  OTP_VERIFY_REQUEST,
  OTP_VERIFY_SUCCESS,
  OTP_VERIFY_FAILURE,
  LOGOUT_USER,
  LOGOUT_USER_SUCCESS,
  LOGOUT_USER_FAILURE,
};
