const OTP_REQUEST = "OTP_REQUEST";
const OTP_REQUEST_SUCCESS = "OTP_REQUEST_SUCCESS";
const OTP_REQUEST_FAILURE = "OTP_REQUEST_FAILURE";
const OTP_VERIFY_REQUEST = "OTP_VERIFY_REQUEST";
const OTP_VERIFY_SUCCESS = "OTP_VERIFY_SUCCESS";
const OTP_VERIFY_FAILURE = "OTP_VERIFY_FAILURE";
export {
  OTP_REQUEST,
  OTP_REQUEST_SUCCESS,
  OTP_REQUEST_FAILURE,
  OTP_VERIFY_REQUEST,
  OTP_VERIFY_SUCCESS,
  OTP_VERIFY_FAILURE,
};
