const OTP_REQUEST = "OTP_REQUEST";
const OTP_REQUEST_SUCCESS = "OTP_REQUEST_SUCCESS";
const OTP_REQUEST_FAILURE = "OTP_REQUEST_FAILURE";

export { OTP_REQUEST, OTP_REQUEST_SUCCESS, OTP_REQUEST_FAILURE };
