const GET_BENEFICIARIES = "GET_BENEFICIARIES";
const GET_BENEFICIARIES_SUCCESS = "GET_BENEFICIARIES_SUCCESS";
const GET_BENEFICIARIES_FAILURE = "GET_BENEFICIARIES_FAILURE";
const DOWNLOAD_CERTIFICATE = "DOWNLOAD_CERTIFICATE";

export {
  GET_BENEFICIARIES,
  GET_BENEFICIARIES_SUCCESS,
  GET_BENEFICIARIES_FAILURE,
  DOWNLOAD_CERTIFICATE,
};
